// gatsby/restaurant/src/templates/about-us.tsx
import React from 'react';
import PageWrapper from '../components/PageWrapper';
import { AboutUsPageContent } from '../types';
import AboutHero from '../components/about-page/Hero';
import AboutTextImage from '../components/about-page/TextImage';

export interface AboutUstTemplateProps {
    pageContext: AboutUsPageContent;
}

const AboutUsTemplate: React.FC<AboutUstTemplateProps> = ({
    pageContext: { meta, bcms },
}) => {
    return (
        <PageWrapper title={`${meta.seo?.title || meta.title} - Tastyyy`}>
            <div>
                <AboutHero
                    title={meta.hero_title}
                    subtitle={meta.hero_subtitle}
                    description={meta.hero_description}
                    cover={meta.hero_cover}
                    bcmsConfig={bcms}
                />
                <AboutTextImage data={meta.text_image_cols} bcmsConfig={bcms} />
            </div>
        </PageWrapper>
    );
};

export default AboutUsTemplate;

// nuxt/restaurant/pages/about-us/index.vue
<template>
    <div v-if="data">
        <AboutPageHero
            :title="data.meta.hero_title"
            :subtitle="data.meta.hero_subtitle"
            :description="data.meta.hero_description"
            :cover="data.meta.hero_cover"
            :bcms="data.bcms"
        />
        <AboutPageTextImage
            :data="data.meta.text_image_cols"
            :bcms="data.bcms"
        />
    </div>
</template>

<script setup lang="ts">
import type { AboutUsPageResponse } from '~/server/api/about-us-page';

const { setOgHead } = useHeadTags();

const { data, error } =
    await useFetch<AboutUsPageResponse>('/api/about-us-page');

if (!data.value || error.value) {
    throw createError({
        statusCode: 404,
        statusMessage: 'Page Not Found',
    });
}

useHead(() =>
    setOgHead({
        title: `${data.value?.meta.seo?.title || data.value?.meta.title} - Tastyyy`,
        description: data.value?.meta.seo?.description,
    }),
);
</script>
