// nuxt/agency/pages/team.vue
<template>
    <div v-if="data">
        <Hero
            :title="data.meta.title"
            subtitle="Team"
            :description="data.meta.description"
        />
        <TeamList :items="data.members" :bcms="data.bcms" />
        <ContactBlock
            :title="data.meta.contact_title"
            :description="data.meta.contact_description"
        />
    </div>
</template>

<script setup lang="ts">
import type { TeamPageResponse } from '~/server/api/team-page';

const { setOgHead } = useHeadTags();

const { data, error } = await useFetch<TeamPageResponse>('/api/team-page');

if (!data.value || error.value) {
    throw createError({
        statusCode: 404,
        statusMessage: 'Page Not Found',
    });
}

useHead(() =>
    setOgHead({
        title: data.value?.meta.seo?.title || data.value?.meta.title,
        description: data.value?.meta.seo?.description,
    }),
);
</script>

// gatsby/agency/src/templates/team.tsx
import React from 'react';
import PageWrapper from '../components/PageWrapper';
import { TeamPageContent } from '../types';
import Hero from '../components/Hero';
import ContactBlock from '../components/ContactBlock';
import TeamList from '../components/team-page/List';

export interface TeamTemplateProps {
    pageContext: TeamPageContent;
}

const TeamTemplate: React.FC<TeamTemplateProps> = ({
    pageContext: { meta, entries, bcms },
}) => {
    return (
        <PageWrapper title={`${meta.seo?.title || meta.title} - BrandCrafters`}>
            <Hero
                title={meta.title}
                subtitle="Team"
                description={meta.description}
            />
            <TeamList items={entries} bcmsConfig={bcms} />
            <ContactBlock
                title={meta.contact_title}
                description={meta.contact_description}
            />
        </PageWrapper>
    );
};

export default TeamTemplate;
