// astro/job-board/src/components/home-page/Hero.tsx
import React, { type FC } from 'react';
import { BCMSImage } from '@thebcms/components-react';
import type { InlineTextWithImageGroup } from '../../../bcms/types/ts';
import type { PropMediaDataParsed, PropRichTextDataParsed } from '@thebcms/types';
import type { ClientConfig } from '@thebcms/client';
import ContentManager from '../ContentManager';
import Btn from '../Btn';

interface Props {
    title: InlineTextWithImageGroup[];
    description: PropRichTextDataParsed;
    cover: PropMediaDataParsed;
    bcmsConfig: ClientConfig;
}

const HomeHero: FC<Props> = ({ title, description, cover, bcmsConfig }) => {
    const scrollToJobs = () => {
        const jobs = document.getElementById('homeJobs');

        if (jobs) {
            jobs.scrollIntoView({ behavior: 'smooth' });
        }
    };

    return (
        <section className="pt-10 lg:pt-[104px]">
            <div className="container">
                <div className="max-w-[250px] mx-auto md:max-w-[350px] lg:max-w-[840px]">
                    <h1 className="mb-4 lg:mb-8 [&_*]:inline">
                        {title.map((item, index) => (
                            <React.Fragment key={index}>
                                {item.text && item.text.nodes.length > 0 && (
                                    <ContentManager
                                        items={item.text.nodes}
                                        className="text-2xl leading-[1.4] font-medium font-PlayfairDisplay tracking-[-0.41px] md:text-4xl lg:text-[80px] lg:leading-[1.1]"
                                    />
                                )}
                                {item.image && (
                                    <BCMSImage
                                        key={index}
                                        media={item.image}
                                        clientConfig={bcmsConfig}
                                        className="inline-block object-cover w-[53px] h-6 flex-shrink-0 -translate-y-1 mx-1 bg-center bg-cover lg:w-[176px] lg:h-20 lg:mx-3 lg:-translate-y-5"
                                    />
                                )}
                            </React.Fragment>
                        ))}
                    </h1>
                    <ContentManager
                        items={description.nodes}
                        className="text-sm leading-[1.4] font-medium tracking-[-0.41px] text-center text-appGray-600 mb-8 md:text-base lg:leading-none lg:mb-10"
                    />
                    <Btn
                        className="mx-auto mb-12 lg:mb-[120px]"
                        onClick={scrollToJobs}
                    >
                        <span>Search Jobs Now</span>
                    </Btn>
                </div>
            </div>
            <div className="relative">
                <BCMSImage
                    media={cover}
                    clientConfig={bcmsConfig}
                    className="w-full aspect-[2.76] object-cover lg:aspect-[3.1]"
                />
                <div className="absolute top-0 left-0 w-full h-full bg-black/60" />
            </div>
        </section>
    );
};

export default HomeHero;

// nuxt/restaurant/components/about-page/Hero.vue
<template>
    <section class="pt-[108px] pb-10 overflow-hidden md:pb-14 lg:pt-[218px]">
        <div class="container max-w-[1198px]">
            <ArchWithStar />
            <div
                class="relative px-4 max-w-[400px] mx-auto lg:max-w-[962px] xl:px-0"
            >
                <SvgoAboutUsOutline
                    filled
                    :font-controlled="false"
                    class="absolute w-[220px] right-[30px] lg:w-[822px] lg:-right-4 lg:-top-6"
                />
                <ContentManager
                    :items="title.nodes"
                    class="aboutHero--title relative z-10 text-xl leading-none font-Gloock mb-2 lg:text-[56px] lg:leading-none lg:mb-3"
                />
                <ContentManager
                    :items="subtitle.nodes"
                    class="relative z-10 text-[10px] leading-[1.2] uppercase max-w-max ml-auto mb-10 lg:text-base lg:leading-[1.2] lg:mb-[120px]"
                />
            </div>
            <BCMSImage
                :media="cover"
                :client="bcms"
                class="w-full object-cover aspect-[1.635] mb-4 lg:aspect-[2.67] lg:mb-10"
            />
            <ContentManager
                :items="description.nodes"
                class="text-sm leading-[1.3] tracking-[-0.41px] uppercase text-appGray-700 mb-6 lg:text-[32px] lg:leading-[1.3] lg:mb-14"
            />
            <Btn to="/menu" class="uppercase max-w-max mx-auto">
                <span>Browse menu</span>
            </Btn>
        </div>
    </section>
</template>

<script setup lang="ts">
import type { ClientConfig } from '@thebcms/client';
import { BCMSImage } from '@thebcms/components-vue';
import type {
    PropMediaDataParsed,
    PropRichTextDataParsed,
} from '@thebcms/types';

defineProps({
    title: {
        type: Object as PropType<PropRichTextDataParsed>,
        required: true,
    },
    subtitle: {
        type: Object as PropType<PropRichTextDataParsed>,
        required: true,
    },
    description: {
        type: Object as PropType<PropRichTextDataParsed>,
        required: true,
    },
    cover: {
        type: Object as PropType<PropMediaDataParsed>,
        required: true,
    },
    bcms: {
        type: Object as PropType<ClientConfig>,
        required: true,
    },
});
</script>

<style lang="scss">
.aboutHero--title {
    h1 {
        @apply flex flex-col gap-1.5 lg:gap-3;
        u {
            @apply no-underline;
        }
        br ~ u {
            @apply text-right;
        }
    }
}
</style>
