// next/agency/nuxt/agency/pages/services.vue
<template>
  <PageWrapper v-if="data" :header="data.header" :footer="data.footer">
    <Hero
      :title="data.page.meta.title"
      subtitle="Our services"
      :description="data.page.meta.description"
    />
    <ServicesList :services="data.page.meta.services" />
    <ContactBlock :data="data.page.meta.contact_block" />
  </PageWrapper>
</template>

<script setup lang="ts">
import { NuxtApp } from 'nuxt/app';
import { ServicesPageEntry, ServicesPageEntryMeta } from '~~/bcms/types';
import { PageProps, ServicesPageData } from '~~/types';
import { getHeaderAndFooter } from '~~/utils/page-data';

const { data, error } = useAsyncData<PageProps<ServicesPageData> | undefined>(
  'services',
  async (ctx) => {
    const { header, footer } = await getHeaderAndFooter(ctx as NuxtApp);
    // Get Services Page entry
    const servicesPage = (await ctx?.$bcms.entry.get({
      template: 'services_page',
      entry: 'services',
    })) as ServicesPageEntry;
    if (!servicesPage) {
      throw new Error('Services page entry does not exist.');
    }
    return {
      header,
      footer,
      page: {
        // Return Services Page entry for `en` locale
        meta: servicesPage.meta.en as ServicesPageEntryMeta,
      },
    };
  },
);
if (error.value) {
  throw createError({
    statusCode: 500,
    statusMessage: error.value.message,
    stack: error.value.stack,
    fatal: true,
  });
}

const { setOgHead } = useHeadTags();

useHead(() =>
  setOgHead({
    title: data.value?.page.meta.seo?.title || data.value?.page.meta.title,
    description: data.value?.page.meta.seo?.description,
  }),
);
</script>

// gatsby/agency/src/pages/services.tsx
import React from 'react';
import { PageWrapper } from '@/components/PageWrapper';

import {
  ServiceEntry,
  ServicesPageEntryMeta,
  FooterEntryMeta,
  HeaderEntryMeta,
} from '../../bcms/types';

import ContactBlock from '@/components/ContactBlock';
import { graphql } from 'gatsby';
import { BCMSPropRichTextDataParsed } from '@becomes/cms-client/types';
import Hero from '@/components/Hero';
import Services from '@/components/services/List';

const ServicesPage: React.FC<{
  data: {
    header: {
      bcms: {
        meta: {
          en: HeaderEntryMeta;
        };
      };
    };
    footer: {
      bcms: {
        meta: {
          en: FooterEntryMeta;
        };
      };
    };
    page: {
      bcms: {
        meta: {
          en: ServicesPageEntryMeta;
        };
        content: {
          en: BCMSPropRichTextDataParsed;
        };
      };
    };
    services: {
      nodes: Array<{
        bcms: ServiceEntry;
      }>;
    };
  };
}> = ({ data }) => {
  
  return (
    <PageWrapper
      header={data.header}
      footer={data.footer}
      page={data.page}
      location="/services"
    >
      {
        <>
          <Hero
            title={data.page.bcms.meta.en.title}
            subtitle="Our Services"
            description={data.page.bcms.meta.en.description}
          />
          <Services services={data.services.nodes} />
          <ContactBlock data={data.page.bcms.meta.en.contact_block} />
        </>
      }
    </PageWrapper>
  );
};

export const query = graphql`
  query {
    header: bcmsHeader {
      ...Header
    }
    footer: bcmsFooter {
      ...Footer
    }
    page: bcmsServicesPage {
      ...Services
    }
    services: allBcmsService {
      nodes {
        ...AllServices
      }
    }
  }
`;

export default ServicesPage;
