// nuxt/personal/components/form/Text.vue
<template>
  <label class="flex flex-col">
    <div
      v-if="label"
      class="text-sm leading-none tracking-[-0.41px] pb-3 border-b border-[#D9D9D9] transition-colors duration-300 lg:text-base lg:leading-none lg:pb-4"
      :class="[error ? 'text-red-500' : '']"
    >
      {{ label }}
    </div>
    <div class="flex items-center">
      <ArrowIcon
        v-if="!isReadOnly"
        class="w-[14px] h-[14px] mr-2 lg:w-4 lg:h-4 lg:mr-2.5"
      />
      <input
        :value="modelValue"
        :type="type"
        :placeholder="placeholder"
        :readonly="isReadOnly"
        class="bg-transparent py-3 text-sm leading-none tracking-[-0.41px] w-full placeholder:text-appGray-400 focus:outline-none lg:py-4 lg:text-base lg:leading-none"
        @input="handleInput"
      />
    </div>
  </label>
</template>

<script setup lang="ts">
import { PropType } from "vue";
import ArrowIcon from "@/assets/icons/arrow.svg";

defineProps({
  modelValue: {
    type: String,
    required: true,
  },
  label: {
    type: String,
    required: false,
  },
  placeholder: {
    type: String,
    required: false,
  },
  type: {
    type: String as PropType<"text" | "email">,
    required: false,
    default: "text",
  },
  isReadOnly: {
    type: Boolean,
    required: false,
    default: false,
  },
  error: {
    type: String,
    required: false,
  },
});

const emits = defineEmits(["update:modelValue"]);

const handleInput = (event: Event) => {
  const target = event.target as HTMLInputElement;

  emits("update:modelValue", target.value);
};
</script>

// next/personal/components/form/Text.tsx
import ArrowIcon from '@/assets/icons/arrow.svg';

import { ChangeEvent } from 'react';
import classNames from 'classnames';
interface FormTextProps {
  value: string;
  type?: 'email' | 'text';
  isReadOnly?: boolean;
  placeholder?: string;
  label?: string;

  onChange?: (value: string) => void;

  className?: string;
}
const FormText: React.FC<FormTextProps> = ({
  onChange,
  label,
  type = 'text',
  value,
  isReadOnly,
  placeholder,
  className,
}) => {
  const handleInput = (
    event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    if (onChange !== undefined) {
      onChange(event.target.value);
    }
  };

  return (
    <label className={classNames('flex flex-col', className)}>
      {label && (
        <div className="text-sm leading-none tracking-[-0.41px] pb-3 border-b border-[#D9D9D9] transition-colors duration-300 lg:text-base lg:leading-none lg:pb-4">
          {label}
        </div>
      )}
      <div className="flex items-center">
        {!isReadOnly && (
          <ArrowIcon className="w-[14px] h-[14px] mr-2 lg:w-4 lg:h-4 lg:mr-2.5" />
        )}
        <input
          value={value}
          type={type}
          placeholder={placeholder}
          readOnly={isReadOnly}
          className="bg-transparent py-3 text-sm leading-none tracking-[-0.41px] w-full placeholder:text-appGray-400 focus:outline-none lg:py-4 lg:text-base lg:leading-none"
          onChange={handleInput}
        />
      </div>
    </label>
  );
};

export default FormText;
