// nuxt/personal/website/components/AnimatedTitle.vue
<template>
  <div class="flex">
    <component :is="tag" ref="titleDOM" :class="titleClass">
      {{ title }}
    </component>
  </div>
</template>

<script setup lang="ts">
defineProps({
  tag: {
    type: String,
    required: false,
    default: "h1",
  },
  title: {
    type: String,
    required: true,
  },
  titleClass: {
    type: String,
    required: false,
    default: "",
  },
});

const { $gsap: gsap } = useNuxtApp();

const titleDOM = ref<HTMLHeadingElement>();

onMounted(() => {
  if (titleDOM.value) {
    gsap.to(titleDOM.value, {
      x: "-100%",
      scrollTrigger: {
        start: "top left",
        end: "bottom right",
        scrub: true,
      },
    });
  }
});
</script>

// gatsby/personal/src/components/AnimatedTitle.tsx
import React, { useRef, useEffect } from 'react';
import { gsap } from 'gsap';
import classNames from 'classnames';

interface TitleProps {
  title: string;
  titleClassName?: string;
  className?: string;
}

const Title: React.FC<TitleProps> = ({
  title,
  titleClassName = '',
  className = '',
}) => {
  const titleRef = useRef<HTMLHeadingElement>(null);

  useEffect(() => {
    if (titleRef.current) {
      const containerWidth =
        document.querySelector('.container')?.clientWidth || 0;

      gsap.to(titleRef.current, {
        x: containerWidth - titleRef.current.clientWidth,
        scrollTrigger: {
          start: 'top left',
          end: 'bottom right',
          scrub: 1,
        },
      });
    }
  }, []);
  return (
    <div className="flex">
      <h1 ref={titleRef} className={classNames(className, titleClassName)}>
        {title}
      </h1>
    </div>
  );
};

export default Title;
