// gatsby/agency/src/components/Error.tsx
import React from 'react';
import { navigate } from 'gatsby';
import { ReactComponent as SvgoArrow } from '@/assets/icons/arrow.svg';

const ErrorPage = () => {
  const goBack = () => {
    navigate('/');
  };

  return (
    <div className="w-screen h-[calc(100vh-150px)] flex flex-col gap-6 items-center justify-center lg:gap-10">
      <h1 className="text-3xl font-semibold text-center md:text-4xl lg:text-5xl">
        Error page
      </h1>
      <button
        className="flex items-center px-[15px] py-2.5 text-appText-light bg-appAccent-300 rounded-[32px] transition-colors duration-300 hover:bg-appAccent"
        onClick={goBack}
      >
        <span className="text-sm leading-none tracking-[-0.41px] mr-1.5 md:text-base md:leading-none md:mr-2 lg:text-xl lg:leading-none">
          Go back home
        </span>
        <SvgoArrow className="w-[14px] h-[14px] md:w-4 md:h-4 lg:w-5 lg:h-5" />
      </button>
    </div>
  );
};

export default ErrorPage;

// next/agency/nuxt/conference/components/Error.vue
<template>
  <div
    class="w-screen h-[calc(100vh-150px)] flex flex-col gap-6 items-center justify-center lg:gap-10"
  >
    <h1 class="text-3xl font-semibold text-center md:text-4xl lg:text-5xl">
      Error page
    </h1>
    <button
      class="flex items-center px-5 py-[13px] bg-black rounded-[48px] lg:col-start-2 lg:row-start-1 lg:px-[26px] lg:py-[19px]"
      @click="goBack"
    >
      <span
        class="text-sm leading-none tracking-[-0.41px] font-semibold text-white uppercase mr-2 lg:text-lg lg:leading-none"
      >
        Go back home
      </span>
      <ArrowIcon class="w-[14px] h-[14px] text-white lg:w-[18px] lg:h-[18px]" />
    </button>
  </div>
</template>

<script setup lang="ts">
import ArrowIcon from '@/assets/icons/arrow.svg';

const goBack = () => clearError({ redirect: '/' });
</script>
