// next/hospitale/components/Btn.tsx
import { FC } from 'react';
import Link from 'next/link';
import classnames from 'classnames';

import ArrowIcon from '@/../../blog/assets/icons/arrow.svg';

interface ButtonProps {
  className?: string;
  to?: string;
  theme?: 'accent' | 'pale' | 'dark' | 'accent-outline';
  hideArrow?: boolean;
  tag?: string;
  size?: 'sm' | 'regular';

  onClick?: () => void;
}

const Button: FC<ButtonProps> = ({
  className,
  to,
  theme = 'accent',
  hideArrow,
  size = 'regular',
  children,
  onClick,
}) => {
  const showArrow = false;

  const buttonClasses = classnames(
    'group relative flex items-center text-sm leading-none font-medium tracking-[-0.41px] px-5 rounded-[32px] border transition-all duration-300 focus:outline-none hover:px-7 lg:px-7',
    {
      'bg-appAccent text-white border-transparent': theme === 'accent',
      'bg-appAccent/10 text-appAccent border-transparent': theme === 'pale',
      'bg-appText text-white border-transparent': theme === 'dark',
      'border border-appAccent text-appAccent': theme === 'accent-outline',
      'py-3 lg:py-4': size === 'sm',
      'py-4 lg:py-5': size === 'regular',
    },
    className,
  );

  return (
    <div>
      {to ? (
        <Link href={to}>
          <a className={buttonClasses}>{children}</a>
        </Link>
      ) : (
        <button onClick={onClick} className={buttonClasses}>
          {children}
        </button>
      )}
      {showArrow && !hideArrow && (
        <div className="w-[14px] h-[14px] opacity-0 ml-2 transition-all duration-300 group-hover:opacity-100">
          <ArrowIcon />
        </div>
      )}
    </div>
  );
};

export default Button;

// nuxt/hospitale/website/components/Btn.vue
<template>
  <component
    :is="tag ? tag : to ? NuxtLink : 'button'"
    :to="to"
    class="group relative flex items-center text-sm leading-none font-medium tracking-[-0.41px] px-5 rounded-[32px] border transition-all duration-300 focus:outline-none hover:px-7 lg:px-7"
    :class="[
      theme === 'accent'
        ? 'bg-appAccent text-white border-transparent'
        : theme === 'pale'
        ? 'bg-appAccent/10 text-appAccent border-transparent'
        : theme === 'dark'
        ? 'bg-appText text-white border-transparent'
        : 'border border-appAccent text-appAccent',
      size === 'sm' ? 'py-3 lg:py-4' : 'py-4 lg:py-5',
    ]"
    @mouseover="showArrow = true"
    @mouseleave="showArrow = false"
  >
    <slot />
    <Transition name="scaleBtnArrow">
      <ArrowIcon
        v-if="showArrow && !hideArrow"
        class="w-[14px] h-[14px] opacity-0 ml-2 transition-all duration-300 group-hover:opacity-100"
      />
    </Transition>
  </component>
</template>

<script setup lang="ts">
import { PropType } from "vue";
import ArrowIcon from "@/assets/icons/arrow.svg";

defineProps({
  to: {
    type: String,
    required: false,
  },
  theme: {
    type: String as PropType<"accent" | "pale" | "dark" | "accent-outline">,
    required: false,
    default: "accent",
  },
  hideArrow: Boolean,
  tag: {
    type: String,
    required: false,
  },
  size: {
    type: String as PropType<"sm" | "regular">,
    required: false,
    default: "regular",
  },
});

const NuxtLink = resolveComponent("NuxtLink");

const showArrow = ref(false);
</script>
