// nuxt/recipes/website/components/home-page/LetsTalk.vue
<template>
  <section class="relative pb-8 lg:pb-20 xl:pb-[120px]">
    <div class="container">
      <div
        class="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-20 lg:items-center xl:gap-[114px] xl:pr-20"
      >
        <div
          class="flex flex-col items-center text-center lg:items-start lg:text-left"
        >
          <h2
            class="leading-none font-semibold tracking-[-0.41px] text-appGray-700 mb-[14px] lg:text-4xl lg:leading-none lg:mb-6"
          >
            {{ data.title }}
          </h2>
          <ContentManager
            :item="data.description"
            class="text-sm leading-normal font-medium tracking-[-0.41px] text-appGray-500 mb-6 lg:text-lg lg:leading-normal lg:mb-14"
          />
          <div class="grid grid-cols-1 gap-5 lg:gap-10">
            <div
              v-for="(link, index) in data.links"
              :key="index"
              class="flex flex-col items-center lg:items-start"
            >
              <div class="flex items-center mb-2 lg:mb-4">
                <BCMSImage
                  :media="link.icon"
                  class="w-3 h-3 mr-1.5 lg:w-[18px] lg:h-[18px]"
                />
                <div
                  class="text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 lg:text-lg lg:leading-none"
                >
                  {{ link.label }}
                </div>
              </div>
              <ContentManager
                :item="link.link"
                class="text-sm leading-none font-medium tracking-[-0.41px] text-appGray-600 lg:text-2xl lg:leading-none"
              />
            </div>
          </div>
        </div>
        <form
          @submit.prevent="handleSubmit"
          class="border border-[#E0E0E0] rounded-lg p-4 lg:p-8"
        >
          <label
            class="relative flex border rounded-lg overflow-hidden w-full mb-3 transition-colors duration-300 lg:mb-6"
            :class="[form.name.error ? 'border-red-500' : 'border-[#F0F0F0]']"
          >
            <input
              v-model="form.name.value"
              type="text"
              class="w-full text-xs leading-none tracking-[-0.41px] font-medium px-4 py-[14px] focus:outline-none lg:px-6 lg:py-[15px] lg:text-base lg:leading-none"
            />
            <span
              v-if="!form.name.value"
              class="absolute top-1/2 left-4 -translate-y-1/2 text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 pointer-events-none lg:left-6 lg:text-base lg:leading-none"
            >
              Full name<span class="text-appWarning">*</span>
            </span>
          </label>
          <label
            class="relative flex border rounded-lg overflow-hidden w-full mb-3 transition-colors duration-300 lg:mb-6"
            :class="[form.name.error ? 'border-red-500' : 'border-[#F0F0F0]']"
          >
            <input
              v-model="form.email.value"
              type="email"
              class="w-full text-xs leading-none tracking-[-0.41px] font-medium px-4 py-[14px] focus:outline-none lg:px-6 lg:py-[15px] lg:text-base lg:leading-none"
            />
            <span
              v-if="!form.email.value"
              class="absolute top-1/2 left-4 -translate-y-1/2 text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 pointer-events-none lg:left-6 lg:text-base lg:leading-none"
            >
              Email<span class="text-appWarning">*</span>
            </span>
          </label>
          <label
            class="relative flex border rounded-lg overflow-hidden w-full mb-6 transition-colors duration-300 lg:mb-8"
            :class="[form.name.error ? 'border-red-500' : 'border-[#F0F0F0]']"
          >
            <textarea
              v-model="form.question.value"
              class="w-full text-xs leading-none tracking-[-0.41px] font-medium px-4 py-[14px] resize-none h-[140px] focus:outline-none lg:px-6 lg:py-[15px] lg:text-base lg:leading-none lg:h-[260px]"
            />
            <span
              v-if="!form.question.value"
              class="absolute top-5 left-4 -translate-y-1/2 text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 pointer-events-none lg:left-6 lg:text-base lg:leading-none lg:top-6"
            >
              Question<span class="text-appWarning">*</span>
            </span>
          </label>
          <Btn theme="dark" class="justify-center w-full">
            <span>Submit</span>
          </Btn>
        </form>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { PropType } from "vue";
import { BCMSImage } from "~~/bcms-components";
import { HomeLetsTalkGroup } from "~~/bcms/types";

defineProps({
  data: {
    type: Object as PropType<HomeLetsTalkGroup>,
    required: true,
  },
});

const { checkForInputErrors } = useError();

const form = ref({
  name: {
    value: "",
    error: "",
  },
  email: {
    value: "",
    error: "",
  },
  question: {
    value: "",
    error: "",
  },
});

const handleSubmit = () => {
  const errors = checkForInputErrors([
    form.value.name,
    form.value.email,
    form.value.question,
  ]);

  if (!errors) {
    // TODO: Submit
  }
};
</script>

// next/recipes/components/home-page/LetsTalk.tsx
import React, { useState, FormEvent } from 'react';
import { BCMSImage } from 'next-plugin-bcms/components';
import ContentManager from '@/components/ContentManager';
import { HomeLetsTalkGroup } from '@/bcms/types';
import classnames from 'classnames';
import Btn from '@/components/Btn';

interface ContactForm {
  name: string;
  email: string;
  question: string;
}

interface HomepageLetsTalkProps {
  data: HomeLetsTalkGroup;
}

const HomepageLetsTalk: React.FC<HomepageLetsTalkProps> = ({ data }) => {
  const [form, setForm] = useState<ContactForm>({
    email: '',
    name: '',
    question: '',
  });

  const [formErrors, setFormErrors] = useState<
    Record<keyof ContactForm, boolean>
  >({
    email: false,
    name: false,
    question: false,
  });

  const handleSubmit = (e?: FormEvent<HTMLFormElement>) => {
    e?.preventDefault();

    setFormErrors({
      email: false,
      name: false,
      question: false,
    });

    // Validate form fields
    const errors: Record<string, boolean> = {};
    if (!form.name) {
      errors.name = true;
    }
    if (!form.email) {
      errors.email = true;
    }
    if (!form.question) {
      errors.question = true;
    }

    if (Object.keys(errors).length > 0) {
      setFormErrors(errors);
    } else {
      // Submit the form if there are no errors
    }
  };

  return (
    <section className="relative pb-8 lg:pb-20 xl:pb-[120px]">
      <div className="container">
        <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:gap-20 lg:items-center xl:gap-[114px] xl:pr-20">
          <div className="flex flex-col items-center text-center lg:items-start lg:text-left">
            <h2 className="leading-none font-semibold tracking-[-0.41px] text-appGray-700 mb-[14px] lg:text-4xl lg:leading-none lg:mb-6">
              {data.title}
            </h2>
            <ContentManager
              item={data.description}
              className="text-sm leading-normal font-medium tracking-[-0.41px] text-appGray-500 mb-6 lg:text-lg lg:leading-normal lg:mb-14"
            />
            <div className="grid grid-cols-1 gap-5 lg:gap-10">
              {data.links.map((link, index) => (
                <div
                  key={index}
                  className="flex flex-col items-center lg:items-start"
                >
                  <div className="flex items-center mb-2 lg:mb-4">
                    <BCMSImage
                      media={link.icon}
                      className="w-3 h-3 mr-1.5 lg:w-[18px] lg:h-[18px]"
                    />
                    <div className="text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 lg:text-lg lg:leading-none">
                      {link.label}
                    </div>
                  </div>
                  <ContentManager
                    item={link.link}
                    className="text-sm leading-none font-medium tracking-[-0.41px] text-appGray-600 lg:text-2xl lg:leading-none"
                  />
                </div>
              ))}
            </div>
          </div>
          <form
            onSubmit={(e) => handleSubmit(e)}
            className="border border-[#E0E0E0] rounded-lg p-4 lg:p-8"
          >
            <label
              className={classnames(
                'relative flex border rounded-lg overflow-hidden w-full mb-3 transition-colors duration-300 lg:mb-6',
                {
                  'border-red-500': formErrors.name,
                  'border-[#F0F0F0]': !formErrors.name,
                },
              )}
            >
              <input
                onChange={({ target }) =>
                  setForm((prev) => ({ ...prev, ['name']: target.value }))
                }
                value={form.name}
                type="text"
                className="w-full text-xs leading-none tracking-[-0.41px] font-medium px-4 py-[14px] focus:outline-none lg:px-6 lg:py-[15px] lg:text-base lg:leading-none"
              />
              {!form.name.length && (
                <span className="absolute top-1/2 left-4 -translate-y-1/2 text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 pointer-events-none lg:left-6 lg:text-base lg:leading-none">
                  Full name<span className="text-appWarning">*</span>
                </span>
              )}
            </label>
            <label
              className={classnames(
                'relative flex border rounded-lg overflow-hidden w-full mb-3 transition-colors duration-300 lg:mb-6',
                {
                  'border-red-500': formErrors.email,
                  'border-[#F0F0F0]': !formErrors.email,
                },
              )}
            >
              <input
                onChange={({ target }) =>
                  setForm((prev) => ({ ...prev, ['email']: target.value }))
                }
                value={form.email}
                type="email"
                className="w-full text-xs leading-none tracking-[-0.41px] font-medium px-4 py-[14px] focus:outline-none lg:px-6 lg:py-[15px] lg:text-base lg:leading-none"
              />
              {!form.email.length && (
                <span className="absolute top-1/2 left-4 -translate-y-1/2 text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 pointer-events-none lg:left-6 lg:text-base lg:leading-none">
                  Email<span className="text-appWarning">*</span>
                </span>
              )}
            </label>
            <label
              className={classnames(
                'relative flex border rounded-lg overflow-hidden w-full mb-6 transition-colors duration-300 lg:mb-8',
                {
                  'border-red-500': formErrors.question,
                  'border-[#F0F0F0]': !formErrors.question,
                },
              )}
            >
              <textarea
                onChange={({ target }) =>
                  setForm((prev) => ({ ...prev, ['question']: target.value }))
                }
                value={form.question}
                className="w-full text-xs leading-none tracking-[-0.41px] font-medium px-4 py-[14px] resize-none h-[140px] focus:outline-none lg:px-6 lg:py-[15px] lg:text-base lg:leading-none lg:h-[260px]"
              />
              {!form.question && (
                <span className="absolute top-5 left-4 -translate-y-1/2 text-xs leading-none font-medium tracking-[-0.41px] text-appGray-500 pointer-events-none lg:left-6 lg:text-base lg:leading-none lg:top-6">
                  Question<span className="text-appWarning">*</span>
                </span>
              )}
            </label>
            <Btn
              onClick={() => handleSubmit()}
              theme="dark"
              className="justify-center w-full"
            >
              <span>Submit</span>
            </Btn>
          </form>
        </div>
      </div>
    </section>
  );
};

export default HomepageLetsTalk;
