// nuxt/blog/components/PageWrapper.vue
<template>
  <div class="overflow-hidden">
    <LayoutHeader :data="header" />
    <main>
      <slot />
    </main>
    <LayoutFooter :data="footer" />
  </div>
</template>

<script setup lang="ts">
import { PropType } from 'vue';
import { FooterEntryMeta, HeaderEntryMeta } from '~~/bcms/types';

defineProps({
  header: {
    type: Object as PropType<HeaderEntryMeta>,
    required: true,
  },
  footer: {
    type: Object as PropType<FooterEntryMeta>,
    required: true,
  },
});
</script>

// next/blog/components/PageWrapper.tsx

import {Header} from './layout/Header';
import {Footer} from './layout/Footer';
import { HeaderEntryMeta, FooterEntryMeta } from '~~/bcms/types';
import React, {PropsWithChildren} from "react";

interface PageWrapperI {
    header: HeaderEntryMeta;
    footer: FooterEntryMeta;
}
export const PageWrapper: React.FC<PropsWithChildren<PageWrapperI>> = ({header, children, footer}) => {
    return (
        <div className="overflow-hidden">
            <Header data={header} />
            <main>{children}</main>
            <Footer data={footer} />
        </div>
    )
}
