// next/e-commerce/src/app/shop/[slug]/components/Gallery.tsx
'use client';

import React, { useMemo, useState } from 'react';
import classNames from 'classnames';
import { ProductColorEntry, ProductImageGroup } from '@bcms-types/types/ts';
import { BCMSImage } from '@thebcms/components-react';
import { ClientConfig } from '@thebcms/client';

interface Props {
    gallery: ProductImageGroup[];
    activeColor: ProductColorEntry;
    bcms: ClientConfig;
}

export const Gallery: React.FC<Props> = ({ gallery, activeColor, bcms }) => {
    const [activeImage, setActiveImage] = useState(0);

    const galleryByColor = useMemo(() => {
        setActiveImage(0);
        return gallery.filter(
            (e) => e.color.meta.en?.slug === activeColor.meta.en?.slug,
        );
    }, [gallery, activeColor]);

    return (
        <div className="flex flex-col">
            {galleryByColor[activeImage] && (
                <BCMSImage
                    media={galleryByColor[activeImage].image}
                    clientConfig={bcms}
                    className="flex aspect-square w-full object-cover mb-6 flex-1"
                />
            )}
            <div className="flex gap-4 overflow-x-auto">
                {galleryByColor.map((image, index) => (
                    <button
                        key={index}
                        className={classNames(
                            'group flex flex-shrink-0 w-[124px] aspect-square border p-2 transition-colors duration-300',
                            index === activeImage
                                ? 'border-appText'
                                : 'border-appGray-300',
                        )}
                        onClick={() => setActiveImage(index)}
                    >
                        <div className="overflow-hidden">
                            <BCMSImage
                                media={image.image}
                                clientConfig={bcms}
                                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                            />
                        </div>
                    </button>
                ))}
            </div>
        </div>
    );
};

// nuxt/e-commerce/components/shop-page/Gallery.vue
<template>
    <div class="flex flex-col">
        <div class="aspect-square overflow-hidden mb-6">
            <BCMSImage
                v-for="(image, index) in galleryByColor"
                :key="image.image._id"
                :media="image.image"
                :client="bcms"
                :class="`size-full object-cover flex-1 ${activeImage === index ? 'flex' : 'hidden'}`"
            />
        </div>
        <div class="flex gap-4 overflow-x-auto">
            <button
                v-for="(image, index) in galleryByColor"
                :key="image.image._id"
                class="group flex flex-shrink-0 w-[124px] aspect-square border p-2 transition-colors duration-300"
                :class="[
                    index === activeImage
                        ? 'border-appText'
                        : 'border-appGray-300',
                ]"
                @click="activeImage = index"
            >
                <div class="overflow-hidden">
                    <BCMSImage
                        :media="image.image"
                        :client="bcms"
                        class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                    />
                </div>
            </button>
        </div>
    </div>
</template>

<script setup lang="ts">
import type { ClientConfig } from '@thebcms/client';
import { BCMSImage } from '@thebcms/components-vue';
import type { ProductColorEntry, ProductImageGroup } from '~/bcms/types/ts';

const props = defineProps({
    gallery: {
        type: Array as PropType<ProductImageGroup[]>,
        required: true,
    },
    activeColor: {
        type: Object as PropType<ProductColorEntry>,
        required: true,
    },
    bcms: {
        type: Object as PropType<ClientConfig>,
        required: true,
    },
});

const activeImage = ref(0);

const galleryByColor = computed(() => {
    return props.gallery.filter(
        (e) => e.color.meta.en?.slug === props.activeColor.meta.en?.slug,
    );
});

watch(
    () => props.activeColor,
    () => {
        activeImage.value = 0;
    },
);
</script>
