// nuxt/personal/pages/services.vue
<template>
    <div v-if="data">
        <div
            class="pt-8 pb-10 overflow-hidden md:pb-20 lg:pt-[72px] lg:pb-[120px]"
        >
            <div class="container">
                <AnimatedTitle
                    :title="data.meta.title"
                    class="mb-10 md:mb-20 lg:mb-[192px]"
                    title-class="text-[114px] flex-shrink-0 leading-none font-Helvetica tracking-[1.59px] sm:text-[190px] md:text-[220px] lg:text-[300px] lg:tracking-[5.59px] xl:text-[464px]"
                />
                <div class="grid grid-cols-1 gap-10 lg:gap-[72px]">
                    <div
                        v-for="(service, index) in data.services"
                        :key="index"
                        class="lg:grid lg:grid-cols-[1fr,378px,minmax(auto,1fr)] lg:items-start lg:gap-10"
                    >
                        <div class="flex items-center max-lg:mb-[14px]">
                            <div
                                class="w-1.5 h-1.5 bg-appText rounded-full mr-2 lg:w-2.5 lg:h-2.5 lg:mr-4 lg:mt-2"
                            />
                            <h2
                                class="text-lg leading-none tracking-[-0.41px] font-Helvetica lg:text-[32px] lg:leading-none"
                            >
                                {{ service.title }}
                            </h2>
                        </div>
                        <div class="max-lg:mb-6 lg:max-w-[378px]">
                            <ContentManager
                                :items="service.description.nodes"
                                class="text-sm leading-[1.4] tracking-[-0.41px] text-appGray-400 mb-[14px] lg:text-base lg:leading-[1.4] lg:mb-6"
                            />
                            <div
                                class="leading-none tracking-[-0.41px] font-Helvetica lg:text-xl lg:leading-none"
                            >
                                Start from ${{ service.start_price }}
                            </div>
                        </div>
                        <div class="flex lg:justify-end">
                            <button
                                class="flex justify-center items-center w-full px-6 py-[13px] border border-appGray-200 rounded-[32px] text-appGray-500 transition-colors duration-300 hover:border-appText hover:bg-appText hover:text-white lg:px-10 lg:py-5 lg:w-auto"
                            >
                                <span
                                    class="text-sm leading-none tracking-[-0.41px] font-medium lg:text-2xl lg:leading-none"
                                >
                                    Start project
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import type { ServicesPageResponse } from '~/server/api/services-page';

const { setOgHead } = useHeadTags();

const { data, error } =
    await useFetch<ServicesPageResponse>('/api/services-page');

if (!data.value || error.value) {
    throw createError({
        statusCode: 404,
        statusMessage: 'Page Not Found',
    });
}

useHead(() =>
    setOgHead({
        title: `${data.value?.meta.seo?.title || data.value?.meta.title} - Personal Website`,
        description: data.value?.meta.seo?.description,
    }),
);
</script>

// next/personal/src/app/services/page.tsx
import React from 'react';
import { Metadata } from 'next';
import {
    ServiceEntry,
    ServicesPageEntry,
    ServicesPageEntryMetaItem,
} from '@bcms-types/types/ts';
import AnimatedTitle from '@/components/AnimatedTitle';
import { bcms } from '../bcms-client';
import { notFound } from 'next/navigation';
import ContentManager from '@/components/ContentManager';

const pageTitle = 'Services - Personal Website';
export const metadata: Metadata = {
    title: pageTitle,
    openGraph: {
        title: pageTitle,
    },
    twitter: {
        title: pageTitle,
    },
};

const ServicesPage: React.FC = async () => {
    const servicesPageEntry = (await bcms.entry.getBySlug(
        'services',
        'services-page',
    )) as ServicesPageEntry;

    if (!servicesPageEntry) {
        return notFound();
    }

    const servicesPageMeta = servicesPageEntry.meta
        .en as ServicesPageEntryMetaItem;

    const servicesEntries = (await bcms.entry.getAll(
        'service',
    )) as ServiceEntry[];

    return (
        <div className="pt-8 pb-10 overflow-hidden md:pb-20 lg:pt-[72px] lg:pb-[120px]">
            <div className="container">
                <AnimatedTitle
                    title={servicesPageMeta.title}
                    className="mb-10 md:mb-20 lg:mb-[192px]"
                    titleClassName="text-[114px] flex-shrink-0 leading-none font-Helvetica tracking-[1.59px] sm:text-[190px] md:text-[220px] lg:text-[300px] lg:tracking-[5.59px] xl:text-[464px]"
                />
                <div className="grid grid-cols-1 gap-10 lg:gap-[72px]">
                    {servicesEntries.map((service, index) => (
                        <div
                            key={index}
                            className="lg:grid lg:grid-cols-[1fr,378px,minmax(auto,1fr)] lg:items-start lg:gap-10"
                        >
                            <div className="flex items-center max-lg:mb-[14px]">
                                <div className="w-1.5 h-1.5 bg-appText rounded-full mr-2 lg:w-2.5 lg:h-2.5 lg:mr-4 lg:mt-2" />
                                <h2 className="text-lg leading-none tracking-[-0.41px] font-Helvetica lg:text-[32px] lg:leading-none">
                                    {service.meta.en?.title}
                                </h2>
                            </div>
                            <div className="max-lg:mb-6 lg:max-w-[378px]">
                                <ContentManager
                                    items={
                                        service.meta.en?.description.nodes || []
                                    }
                                    className="text-sm leading-[1.4] tracking-[-0.41px] text-appGray-400 mb-[14px] lg:text-base lg:leading-[1.4] lg:mb-6"
                                />
                                <div className="leading-none tracking-[-0.41px] font-Helvetica lg:text-xl lg:leading-none">
                                    Start from ${service.meta.en?.start_price}
                                </div>
                            </div>
                            <div className="flex lg:justify-end">
                                <button className="flex justify-center items-center w-full px-6 py-[13px] border border-appGray-200 rounded-[32px] text-appGray-500 transition-colors duration-300 hover:border-appText hover:bg-appText hover:text-white lg:px-10 lg:py-5 lg:w-auto">
                                    <span className="text-sm leading-none tracking-[-0.41px] font-medium lg:text-2xl lg:leading-none">
                                        Start project
                                    </span>
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default ServicesPage;
